### ISSUE TITLE
Task Cancelled Exception during runtime - await DetectPacket()

### ISSUE THREAD

**Issue by the88g** [eiannone/CANBus-Triple-Logger#1]
![image](https://cloud.githubusercontent.com/assets/15970278/11325831/2b873b4e-9150-11e5-91cc-a38b749fd5ec.png)

The executable crashes when you click Log disabled after connecting to a CANBus Triple.

I downloaded the source code which compiles without problems, but the same actions throw a "Task Cancelled Exception" error and highlights the "await DetectPacket()" in the OpenPort() method (CBTSerial.cs).

Any ideas?

Thanks in advance.

**Comment by eiannone** [comment]
Maybe this bug was fixed with my recent commits on CANBusTriple-Dll, which I forgot to align in this repository. I suppose you cloned an old snapshot of dll code tree.
Now I've updated the dependency (commit 281cf3eadc350205301755f58791e32a2500f491), pointing to latest dll code, and added a [1.1 release](https://github.com/eiannone/CANBus-Triple-Logger/releases/tag/1.1), too.
Could you please [download it](https://github.com/eiannone/CANBus-Triple-Logger/releases/tag/1.1), or try to fetch and checkout latest code and try again?

If you are going to clone the source code don't forget to update also dll submodule (calling git `submodule init` and `git submodule update`).
I hope it will work.

**Comment by the88g** [comment]
Ah fantastic - now working! 

Thanks very much :+1:
